# Generated by Django 3.1.2 on 2021-03-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
