# Generated by Django 3.1.2 on 2021-03-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_orderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='size',
        ),
    ]
